"""
<<<<<<< HEAD:AuthenticationBypassChecker/GoodAuthenticationBypass2/AuthenticationBypass/settings.py
Django settings for AuthenticationBypass project.
=======
Django settings for pathProject project.
>>>>>>> e4097359620d4ac1ebf96b6107ba72e6496bc76f:PathTraversalChecker/GoodPathTraversal/pathProject/settings.py

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
<<<<<<< HEAD:AuthenticationBypassChecker/GoodAuthenticationBypass2/AuthenticationBypass/settings.py
from django.core.exceptions import ImproperlyConfigured
=======
>>>>>>> e4097359620d4ac1ebf96b6107ba72e6496bc76f:PathTraversalChecker/GoodPathTraversal/pathProject/settings.py

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
<<<<<<< HEAD:AuthenticationBypassChecker/GoodAuthenticationBypass2/AuthenticationBypass/settings.py

### GOOD!
secret_file = os.path.join(BASE_DIR, 'secrets.json')

with open(secret_file) as f:
    secrets = json.loads(f.read())

def get_secret(setting, secrets=secrets):
    try:
        return secrets[setting]
    except KeyError:
        error_msg = "Set the {} environment variable".format(setting)
        raise ImproperlyConfigured(error_msg)

SECRET_KEY = get_secret("SECRET_KEY")

### BAD!
# SECRET_KEY = '@*%brcrkpdn2^arn0qd6c@mx*9my1nvuk&b(1lyu=c5)9h*-nv'


=======
SECRET_KEY = '(+1tf*=yj#$rdpr+f@4t^c1-enwn905)4=1g0-^!@h5vt%o54x'
>>>>>>> e4097359620d4ac1ebf96b6107ba72e6496bc76f:PathTraversalChecker/GoodPathTraversal/pathProject/settings.py

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'users',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions', # 세션 기능
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'pathApp',
    'sendfile',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', # 세션 기능
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

<<<<<<< HEAD:AuthenticationBypassChecker/GoodAuthenticationBypass2/AuthenticationBypass/settings.py
ROOT_URLCONF = 'AuthenticationBypass.urls'
=======
ROOT_URLCONF = 'pathProject.urls'
>>>>>>> e4097359620d4ac1ebf96b6107ba72e6496bc76f:PathTraversalChecker/GoodPathTraversal/pathProject/settings.py

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

<<<<<<< HEAD:AuthenticationBypassChecker/GoodAuthenticationBypass2/AuthenticationBypass/settings.py
WSGI_APPLICATION = 'AuthenticationBypass.wsgi.application'
=======
WSGI_APPLICATION = 'pathProject.wsgi.application'
>>>>>>> e4097359620d4ac1ebf96b6107ba72e6496bc76f:PathTraversalChecker/GoodPathTraversal/pathProject/settings.py


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Rest FrameWork
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ]

}




# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'users.User'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
<<<<<<< HEAD:AuthenticationBypassChecker/GoodAuthenticationBypass2/AuthenticationBypass/settings.py

LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'dashboard'
=======
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'pathProject', 'static')
]

MIDDLEWARE_CLASSES = (
    'phople.middleware.DisableCSRF',
)

# Django sendfile
# 링크: https://pypi.org/project/django-sendfile/

# this is a directory where all files that will be used with sendfile must be located.
SENDFILE_ROOT = os.path.join(BASE_DIR, 'pathProject\\fileDirectory\\')

# internal URL prefix for all files served via sendfile
SENDFILE_URL = os.path.join(BASE_DIR, 'pathProject\\fileDirectory\\')

# 취약점 - for use with django development server only. DO NOT USE IN PRODUCTION.
SENDFILE_BACKEND = 'sendfile.backends.development'

>>>>>>> e4097359620d4ac1ebf96b6107ba72e6496bc76f:PathTraversalChecker/GoodPathTraversal/pathProject/settings.py
